// api/error-report.js
// Generates a structured error report from pa_error_log and optionally emails it
// Called from the app's Settings page or on a schedule
//
// SECURITY (forensic audit Finding 2.3, fixed 27 Apr 2026):
// Previously accepted `userId` from request body without verifying it
// matched the caller. An authenticated user could harvest any other user's
// pa_error_log by passing their userId. Now: userId is derived from the
// verified JWT only.
//
// userEmail is still accepted from the body — it's the "send to" address.
// Since the data fetched is scoped to the authenticated user, the worst
// an attacker can do is email their own data to an external address.

import { createClient } from "@supabase/supabase-js";
import { withSentry } from "./lib/sentry.js";
import { requireAuth } from "./lib/auth.js";

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const userId = await requireAuth(req, res);
  if (!userId) return; // 401 already sent

  const { userEmail, sendEmail = false, daysBack = 7 } = req.body || {};

  const since = new Date(Date.now() - daysBack * 24 * 60 * 60 * 1000).toISOString();

  // Fetch all unreported errors for this user in the time window
  const { data: errors, error: fetchErr } = await supabase
    .from("pa_error_log")
    .select("*")
    .eq("user_id", userId)
    .gte("occurred_at", since)
    .order("occurred_at", { ascending: false });

  if (fetchErr) return res.status(500).json({ error: fetchErr.message });
  if (!errors?.length) return res.json({ report: null, message: "No errors in this period" });

  // Group by type
  const grouped = {};
  for (const e of errors) {
    if (!grouped[e.error_type]) grouped[e.error_type] = [];
    grouped[e.error_type].push(e);
  }

  // Deduplicate within groups — group by error_msg similarity
  const dedup = (items) => {
    const seen = new Map();
    for (const item of items) {
      const key = (item.error_msg || item.context || "").slice(0, 60).toLowerCase();
      if (seen.has(key)) {
        seen.get(key).count++;
        seen.get(key).last = item.occurred_at;
      } else {
        seen.set(key, { ...item, count: 1, last: item.occurred_at });
      }
    }
    return [...seen.values()].sort((a, b) => b.count - a.count);
  };

  // Build the markdown report
  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const totalErrors = errors.length;

  let report = `# Trade PA Error Report\n**Generated:** ${date}  |  **Period:** Last ${daysBack} days  |  **Total events:** ${totalErrors}\n\n---\n\n`;
  report += `> This report was auto-generated by the Trade PA error capture system.\n> Paste this into a Claude session and say "fix these issues in my Trade PA App.jsx".\n\n---\n\n`;

  const sections = [
    { key: "correction",   title: "🔴 PA Corrections (PA got something wrong — user had to correct it)" },
    { key: "tool_failure", title: "🟠 Tool Failures (actions that didn't execute)" },
    { key: "repetition",   title: "🟡 Repeated Requests (user asked same thing twice — first attempt failed)" },
    { key: "tts_failure",  title: "🔵 Voice/TTS Failures (audio didn't play, mic didn't restart)" },
    { key: "sync_failure", title: "⚪ Data Sync Failures (Supabase writes that failed)" },
    { key: "js_error",     title: "⚫ JavaScript Errors (unhandled exceptions)" },
  ];

  for (const { key, title } of sections) {
    const items = grouped[key];
    if (!items?.length) continue;
    const deduped = dedup(items);
    report += `## ${title}\n`;
    report += `**Total occurrences:** ${items.length}\n\n`;
    for (const item of deduped.slice(0, 8)) {
      report += `### ${item.count > 1 ? `[×${item.count}] ` : ""}${item.error_msg || item.context || "Unknown error"}\n`;
      if (item.tool_name) report += `- **Tool:** \`${item.tool_name}\`\n`;
      if (item.user_input) report += `- **User said:** "${item.user_input.slice(0, 120)}"\n`;
      if (item.pa_response) report += `- **PA responded:** "${item.pa_response.slice(0, 120)}"\n`;
      if (item.context && item.context !== item.error_msg) report += `- **Context:** ${item.context.slice(0, 200)}\n`;
      report += `- **Last seen:** ${new Date(item.last || item.occurred_at).toLocaleDateString("en-GB")}\n\n`;
    }
  }

  report += `---\n\n## How to use this report\n\n1. Copy this entire report\n2. Start a new session with Claude and paste it\n3. Say: **"Fix all these issues in my Trade PA App.jsx"**\n4. Claude will work through each issue, produce fixed code, and explain each fix\n\n*Report auto-generated by Trade PA v2 — tradespa.co.uk*\n`;

  // Mark all included errors as reported
  const errorIds = errors.map(e => e.id);
  await supabase.from("pa_error_log").update({ reported: true }).in("id", errorIds);

  // Optionally send via email
  if (sendEmail && userEmail && process.env.SENDGRID_API_KEY) {
    try {
      await fetch("https://api.sendgrid.com/v3/mail/send", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${process.env.SENDGRID_API_KEY}`,
        },
        body: JSON.stringify({
          personalizations: [{ to: [{ email: userEmail }] }],
          from: { email: "reports@tradespa.co.uk", name: "Trade PA Reports" },
          subject: `Trade PA Error Report — ${date} (${totalErrors} events)`,
          content: [{
            type: "text/plain",
            value: report,
          }, {
            type: "text/html",
            value: `<pre style="font-family:monospace;font-size:13px;white-space:pre-wrap">${report.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>`,
          }],
        }),
      });
    } catch(e) {
      console.error("Email send failed:", e.message);
      // Still return the report even if email failed
    }
  }

  return res.json({ report, errorCount: totalErrors });
}

export default withSentry(handler, { routeName: "error-report" });
